### ISSUE TITLE
i got this working in 4.7 send pull?

### ISSUE THREAD

**Issue by sjb8100** [chenjd/TTUI-Framework#2]
I was very curious what this was. Looks like it is a layer that loads on top of NGUI and acts as a data bridge?

It took me a few hours but I think I got it built correctly, I could see the 2x buttons loaded at runtime as a clone. If I sent a pull request would you accept, I see it is not active anymore.

**Comment by chenjd** [comment]
Hi, this is just a toy and it has not been updated for a long time. 
Yes, you can send a pr.
